-- lb_rewards_history — Rewards & Promotions mission / promo ledger
create table if not exists public.lb_rewards_history (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  customer_email text not null,
  activity text not null,
  reward_bfax bigint not null,
  status text not null default 'Success'::text,
  review_url text null,
  constraint lb_rewards_history_pkey primary key (id)
) tablespace pg_default;

create index if not exists idx_rewards_customer on public.lb_rewards_history using btree (customer_email) tablespace pg_default;

-- 프론트(anon/authenticated) 접근 — Supabase 대시보드 또는 마이그레이션에서 적용
-- grant select, insert, update, delete on table public.lb_rewards_history to anon;
-- grant select, insert, update, delete on table public.lb_rewards_history to authenticated;
-- grant select, insert, update, delete on table public.lb_rewards_history to service_role;
