-- lb_rewards_history — Rewards & Promotions mission / promo ledger
create table if not exists public.lb_rewards_history (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  customer_email text not null,
  activity text not null,
  reward_bfax bigint not null,
  status text not null default 'Success'::text,
  review_url text null,
  constraint lb_rewards_history_pkey primary key (id)
) tablespace pg_default;

create index if not exists idx_rewards_customer on public.lb_rewards_history using btree (customer_email) tablespace pg_default;

alter table public.lb_rewards_history enable row level security;

-- 본인 이메일의 미션·프로모션 기록만 조회 (Realtime 구독 포함)
drop policy if exists rewards_history_select_own on public.lb_rewards_history;
create policy rewards_history_select_own on public.lb_rewards_history
  for select to authenticated
  using (lower(customer_email) = lower(auth.jwt() ->> 'email'));
